### ISSUE TITLE
When initiating a WritingSystem get FileNotFoundError for json files

### ISSUE THREAD

**Issue by andjc** [Halvani/alphabetic#1]
Python 3.12.3 on Ubuntu 23.10 , using alphabetic 0.0.5  installed using pip via PyPi. I ran the following code:

```py
from alphabetic import WritingSystem
ws = WritingSystem()
```

and got the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/venv/el/lib/python3.12/site-packages/alphabetic/core.py", line 518, in __init__
    self.__jsonfiles_present()
  File "/home/vagrant/venv/el/lib/python3.12/site-packages/alphabetic/core.py", line 489, in __jsonfiles_present
    raise FileNotFoundError(f"The following json files: {missing_jsonfiles} were not found. Ensure these files exists before performing the instantiation.")
FileNotFoundError: The following json files: ['alphabetic/data/abjad.json', 'alphabetic/data/abugida.json', 'alphabetic/data/alphabet.json', 'alphabetic/data/featural.json', 'alphabetic/data/logographic.json', 'alphabetic/data/syllabary.json', 'alphabetic/data/latin_script_code.json', 'alphabetic/data/iso_639_1-2_codes_en_de_fr.json', 'alphabetic/data/iso_639_3_codes_en.json', 'alphabetic/data/iso_15924_codes.json'] were not found. Ensure these files exists before performing the instantiation.
>>> 
```

In `/home/vagrant/venv/el/lib/python3.12/site-packages/alphabetic/data` there are the following files:

```
abjad.json    alphabet.json  iso_15924_codes.json             iso_639_3_codes_en.json  logographic.json
abugida.json  featural.json  iso_639_1-2_codes_en_de_fr.json  latin_script_code.json   syllabary.json
```

So files are in package, but not found.

**Comment by Halvani** [comment]
Fixed! The problem was related to relative file paths that are checked when WritingSystems is instantiated.
